INSERT INTO `tags` (`id`, `name`, `slug`, `icon`, `image`, `details`, `created_at`, `updated_at`, `deleted_at`) VALUES
(2, 'Sports', 'new-sports', NULL, '{\"id\": 17, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/17/chawkb.sports.png\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/17/conversions/chawkb.sports-thumbnail.jpg\"}', NULL, '2021-10-09 17:17:51', '2021-10-09 17:17:51', NULL),
(4, 'Sunglass', 'exclusive-sunglasses', NULL, '{\"id\": 20, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/20/chawkbsunglass.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/20/conversions/chawkbsunglass-thumbnail.jpg\"}', NULL, '2021-10-09 17:21:17', '2021-10-09 17:21:17', NULL),
(5, 'Coupons', 'product-coupons', NULL, '{\"id\": 21, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/21/chawkbcoupond.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/21/conversions/chawkbcoupond-thumbnail.jpg\"}', NULL, '2021-10-09 17:21:38', '2021-10-09 19:19:47', NULL),
(6, 'Backpack', 'new-backpack', 'HandBags', '{\"id\": 22, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/22/chawkbbackpack.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/22/conversions/chawkbbackpack-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:21:58', '2021-11-29 06:01:58', NULL),
(7, 'Women\'s Collection', 'womens-collection', 'WomenDress', '{\"id\": 23, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/23/chawkbwomen.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/23/conversions/chawkbwomen-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:22:18', '2021-11-29 06:02:04', NULL),
(8, 'Men\'s Collection', 'mens-collection', 'Pants', '{\"id\": 25, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/25/Banner-5.png\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/25/conversions/Banner-5-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:24:03', '2021-11-29 06:02:09', NULL),
(9, 'Flash Sale', 'flash-sale', 'Accessories', '[]', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:26:01', '2021-11-29 06:02:13', NULL),
(10, 'Featured Products', 'featured-products', 'Accessories', '[]', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:41:16', '2021-11-29 06:02:22', NULL),
(11, 'Kids Collection', 'kids-collection', 'Skirts', '{\"id\": 34, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/34/banner-mobile-3.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/34/conversions/banner-mobile-3-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:52:56', '2021-11-29 06:02:30', NULL),
(12, 'Winter Collection', 'winter-collection', 'Accessories', '{\"id\": 35, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/35/banner-1.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/35/conversions/banner-1-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:53:38', '2021-11-29 06:02:33', NULL),
(13, 'Gift Collection', 'gift-collection', 'ShoulderBags', '{\"id\": 36, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/36/banner-2.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/36/conversions/banner-2-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:54:07', '2021-11-29 06:02:43', NULL),
(14, 'Winter Offer', 'winter-offer', 'Accessories', '{\"id\": 37, \"original\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/37/banner-3.jpg\", \"thumbnail\": \"https://chawkbazarlaravel.s3.ap-southeast-1.amazonaws.com/37/conversions/banner-3-thumbnail.jpg\"}', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-09 17:54:24', '2021-11-29 06:02:47', NULL),
(15, 'On Sale', 'on-sale', 'Accessories', '[]', 'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.', '2021-10-26 07:24:07', '2021-11-29 06:02:50', NULL);